### ISSUE TITLE
Feature to install Neovim from Homebrew

### ISSUE THREAD

**Issue by davidagardh** [paul-gilber/devcontainer-features#52]
There currently exist two features to install Neovim. One uses apt-get, but that usually means getting very old versions. The other builds from source, which is very slow, and also doesn't work on some base images. Homebrew would be a convenient way to get the latest version.

**Comment by davidagardh** [comment]
I found this already exists, ghcr.io/devcontainers-contrib/features/neovim-homebrew:1
This can be considered resolved

**Comment by LilTimmyRules** [comment]
Hack code acttack mode shut down your pc
